### ISSUE TITLE
手势滑动转场时动画交界处会回弹出现黑色背景

### ISSUE THREAD

**Issue by liwenDeng** [seedante/iOS-Note#1]
![bug1](https://cloud.githubusercontent.com/assets/12794697/13693888/e2a7c326-e78a-11e5-8a24-8567818baaba.gif)

**Comment by seedante** [comment]
多谢 @liwenDeng 发现这个 Bug 并且找到了解决的办法，具体说明可以查看此处：[fix interactive transition bug in TabBarController](https://github.com/seedante/iOS-ViewController-Transition-Demo/blob/d1df49998ea8971ae202e3275ff07fd7d4575df3/ScrollTabBarController/ScrollTabBarController/ScrollTabBarController.swift)。

**Comment by seedante** [comment]
Close.
